<a href="https://colab.research.google.com/github/minalang/qualification_bigdata/blob/main/220622_%EC%9E%91%EC%97%85%ED%98%952%EC%9C%A0%ED%98%95%EC%98%88%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 작업형 2유형 예제


인프런 빅데이터분석기사 실기 강의 7강 ~ 8강<br>
url = https://www.inflearn.com/course/%EB%B9%85%EB%B6%84%EA%B8%B0-%EC%8B%9C%ED%97%98%EC%8B%A4%EA%B8%B0-%ED%8C%8C%EC%9D%B4%EC%8D%AC/lecture/105439?tab=curriculum


### 1. 데이터 불러오기

In [40]:
# 필요한 패키지 불러오기
import seaborn as sns
import pandas as pd
import numpy as np

# 데이터 불러오기
df = sns.load_dataset('penguins')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    object 
 1   island             344 non-null    object 
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    object 
dtypes: float64(4), object(3)
memory usage: 18.9+ KB


In [41]:
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen            39.1           18.7              181.0   
1  Adelie  Torgersen            39.5           17.4              186.0   
2  Adelie  Torgersen            40.3           18.0              195.0   
3  Adelie  Torgersen             NaN            NaN                NaN   
4  Adelie  Torgersen            36.7           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3          NaN     NaN  
4       3450.0  Female

In [42]:
# 결측치 확인
df.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

### 2. 결측치 처리

In [43]:
#연속형 데이터 결측치 처리
missing = ['bill_length_mm', 'bill_depth_mm', 'flipper_length_mm', 'body_mass_g']
for m in missing:
  df[m] = df[m].fillna(df[m].median())
df.head()

species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  Adelie  Torgersen           39.10           18.7              181.0   
1  Adelie  Torgersen           39.50           17.4              186.0   
2  Adelie  Torgersen           40.30           18.0              195.0   
3  Adelie  Torgersen           44.45           17.3              197.0   
4  Adelie  Torgersen           36.70           19.3              193.0   

   body_mass_g     sex  
0       3750.0    Male  
1       3800.0  Female  
2       3250.0  Female  
3       4050.0     NaN  
4       3450.0  Female

In [44]:
df['sex'].value_counts()

Male      168
Female    165
Name: sex, dtype: int64

In [45]:
df['sex'] = df['sex'].fillna('Male')

In [46]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

### 3. 라벨 인코딩

In [47]:
#범주형 변수에 대해 라벨 인코딩
from sklearn.preprocessing import LabelEncoder
label = ['species', 'island', 'sex']
df[label] = df[label].apply(LabelEncoder().fit_transform)

In [48]:
df.head()

species  island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0        0       2           39.10           18.7              181.0   
1        0       2           39.50           17.4              186.0   
2        0       2           40.30           18.0              195.0   
3        0       2           44.45           17.3              197.0   
4        0       2           36.70           19.3              193.0   

   body_mass_g  sex  
0       3750.0    1  
1       3800.0    0  
2       3250.0    0  
3       4050.0    1  
4       3450.0    0

### 4. 데이터 변환, 더미처리

In [49]:
category = ['island', 'sex']
for c in category:
  df[c] = df[c].astype('category')
df = pd.get_dummies(df)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  
0         0         0         1      0      1  
1         0         0         1      1      0  
2         0         0         1      1      0  
3         0         0         1      0      1  
4         0         0         1      1      0

### 5. 파생변수 만들기

In [50]:
# qcut: 연속형 데이터의 구간을 나눠 새로운 범주형 변수로 나타내어 주는 것
df['body_mass_g_qcut'] = pd.qcut(df['body_mass_g'], 5, labels = False)
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0           39.10           18.7              181.0       3750.0   
1        0           39.50           17.4              186.0       3800.0   
2        0           40.30           18.0              195.0       3250.0   
3        0           44.45           17.3              197.0       4050.0   
4        0           36.70           19.3              193.0       3450.0   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

### 6. 스케일링

In [52]:
from sklearn.preprocessing import MinMaxScaler
scaler = ['bill_length_mm', 'bill_depth_mm','flipper_length_mm', 'body_mass_g']
min = MinMaxScaler()
min.fit(df[scaler])
df[scaler] = min.transform(df[scaler])
df.head()

species  bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g  \
0        0        0.254545       0.666667           0.152542     0.291667   
1        0        0.269091       0.511905           0.237288     0.305556   
2        0        0.298182       0.583333           0.389831     0.152778   
3        0        0.449091       0.500000           0.423729     0.375000   
4        0        0.167273       0.738095           0.355932     0.208333   

   island_0  island_1  island_2  sex_0  sex_1  body_mass_g_qcut  
0         0         0         1      0      1                 1  
1         0         0         1      1      0                 1  
2         0         0         1      1      0                 0  
3         0         0         1      0      1                 2  
4         0         0         1      1      0                 0

In [53]:
corr_matrix = df.corr()
corr_matrix['species'].sort_values(ascending  = False)

species              1.000000
flipper_length_mm    0.850819
body_mass_g          0.747547
bill_length_mm       0.728706
body_mass_g_qcut     0.728582
island_0             0.610710
sex_1                0.010240
sex_0               -0.010240
island_1            -0.311589
island_2            -0.434574
bill_depth_mm       -0.741282
Name: species, dtype: float64

### 7. 데이터 분리

In [54]:
from sklearn.model_selection import train_test_split
X_train,X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df['species'], test_size = 0.2, random_state = 777)

### 8. 모형학습

#### 1) RandomForestClassifier

In [55]:
from sklearn.ensemble import RandomForestClassifier
model1 = RandomForestClassifier()
model1.fit(X_train, y_train)
pred1 = model1.predict(X_test)

In [56]:
pred1

array([0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0,
       0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0,
       0, 0, 2])

#### 2) AdaBoostClassifier

In [59]:
from sklearn.ensemble import AdaBoostClassifier
model2 = AdaBoostClassifier()
model2.fit(X_train, y_train)
pred2 = model2.predict(X_test)
pred2

array([0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0,
       0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0,
       0, 0, 2])

### 9. 앙상블 voting기법


In [60]:
from sklearn.ensemble import VotingClassifier
clf = VotingClassifier(estimators = [('rf', model1), ('ada', model2)], voting = 'hard')
clf.fit(X_train, y_train)
pred3 = clf.predict(X_test)

In [61]:
pred3

array([0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0,
       0, 0, 1, 0, 2, 2, 2, 2, 2, 0, 0, 0, 2, 1, 1, 1, 0, 2, 2, 1, 0, 2,
       0, 2, 2, 0, 2, 0, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 2, 0, 2, 0, 0,
       0, 0, 2])

### 10. 모델 평가

In [62]:
#accuracy score
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
print(f'rf정확도: {accuracy_score(y_test, pred1)}')
print(f'ada정확도: {accuracy_score(y_test, pred2)}')
print(f'voting정확도: {accuracy_score(y_test, pred3)}')

rf정확도: 0.9855072463768116
ada정확도: 0.9855072463768116
voting정확도: 0.9855072463768116


### 11. 하이퍼파라미터 튜닝

In [64]:
from sklearn.model_selection import GridSearchCV
parameters = {'n_estimators':[50, 100], 'max_depth':[4, 6]}
model4 = RandomForestClassifier()
clf = GridSearchCV(estimator = model4, param_grid = parameters, cv = 3)
clf.fit(X_train, y_train)
print(f'최적의 파라미터: {clf.best_params_}')


최적의 파라미터: {'max_depth': 6, 'n_estimators': 100}


### 12. 예측값 저장

In [66]:
pd.DataFrame({'id':y_test.index, 'pred':pred3}).to_csv('00300.csv', index = False)

In [68]:
check  = pd.read_csv('00300.csv')
check.head()

id  pred
0   25     0
1  268     2
2    7     0
3  101     0
4  255     2